include/phasar/PhasarLLVM/IfdsIde/EdgeFunction.h, include/phasar/PhasarLLVM/IfdsIde/EdgeFunctionComposer.h, include/phasar/PhasarLLVM/IfdsIde/EdgeFunctions/AllBottom.h, include/phasar/PhasarLLVM/IfdsIde/EdgeFunctions/AllTop.h, include/phasar/PhasarLLVM/IfdsIde/EdgeFunctions/EdgeIdentity.h, include/phasar/PhasarLLVM/IfdsIde/Problems/IDELinearConstantAnalysis.h, lib/Controller/AnalysisController.cpp, lib/PhasarLLVM/IfdsIde/Problems/IDELinearConstantAnalysis.cpp, unittests/PhasarLLVM/IfdsIde/CMakeLists.txt, unittests/PhasarLLVM/IfdsIde/EdgeFunctionComposerTest.cpp, unittests/PhasarLLVM/IfdsIde/Problems/IDELinearConstantAnalysisTest.cpp, unittests/PhasarLLVM/IfdsIde/Problems/IFDSTaintAnalysisTest.cpp
The Edge-Function-Composer is no longer a nested class of the
Linear-Constant Analysis. Unittests were added to test edge function
compositon.
=> Add Edge-Function-Composer

utils/install-llvm-5.0.1.sh
The LLVM installation script assumes target_dir to be specified with a trailing `/`. Not sure if this is intended or not. If I run the script with `./install-llvm-5.0.1.sh 40 ~/software/llvm`, it will clone the projects into `~/software/llvmllvm-5.0.1`. This patch always appends a `/` in the target_dir path, which doesn't hurt even if the target_dir is specified with a `/`.
=> add slash after target dir

CMakeLists.txt, lib/PhasarLLVM/IfdsIde/CMakeLists.txt, lib/PhasarLLVM/Plugins/CMakeLists.txt, lib/PhasarPass/CMakeLists.txt
Fixed cmake dependencies after llvm-8 update and small issues with building phasar as llvm drop in.
- Added deps to plugins
- Only include gtest for out of tree builds, otherwise, llvm provides gtest
=> Fixed CMake deps for llvm-8

lib/Utils/PAMM.cpp
element destruction in PAMM.cpp:66 invalidates reference parameter TimerId, causing memory corruption
=> fix UAF in PAMM

lib/Config/Configuration.cpp
Prevent crash when HOME is not defined in the environment.
=> Fixes wrong environment lookup during config load.

include/phasar/PhasarLLVM/Utils/TaintConfiguration.h
assert() on just a string will never trigger because string to bool
conversion results in true.
=> Converts wrong asserts to llvm_unreachable

CMakeLists.txt, lib/Config/CMakeLists.txt, lib/Controller/CMakeLists.txt, lib/DB/CMakeLists.txt, lib/Experimental/CMakeLists.txt, lib/PhasarClang/CMakeLists.txt, lib/PhasarLLVM/ControlFlow/CMakeLists.txt, lib/PhasarLLVM/IfdsIde/CMakeLists.txt, lib/PhasarLLVM/Mono/CMakeLists.txt, lib/PhasarLLVM/Passes/CMakeLists.txt, lib/PhasarLLVM/Plugins/CMakeLists.txt, lib/PhasarLLVM/Pointer/CMakeLists.txt, lib/PhasarLLVM/SyncPDS/CMakeLists.txt, lib/PhasarLLVM/Utils/CMakeLists.txt, lib/PhasarLLVM/WPDS/CMakeLists.txt, lib/PhasarPass/CMakeLists.txt, lib/Utils/CMakeLists.txt
The cmake macros add_phasar_library and  add_phasar_executable have specific variables on how to pass options for linking phasar_libs and llvm_components, this commit update phasars to use these.
This fixes RPATH issues when installing phasar with an in tree build.
=> Rewrite phasar cmake to use lib/exec macro linking capabilities

include/phasar/PhasarLLVM/Passes/GeneralStatisticsPass.h, lib/PhasarLLVM/Passes/GeneralStatisticsPass.cpp
*Corrected some typos
*Modified the runOnModule function => number of load instructions are now also counted.
*Added corresponding declaration and getter in header file.
The number of load instructions is also added to the PAMM REG_COUNTER and BOOST_LOG_SEV
=> GeneralStatisticsPass: Added counter for Load instructions

lib/PhasarLLVM/ControlFlow/LLVMBasedICFG.cpp
For these two functions, the function (or the function of the
corresponding instruction) may not be part of the callgraph. In the
original code this resulted in an exception being thrown. With the
modification an empty set is returned instead.
=> Fix get calls for the case the function is not a vertex.

CMakeLists.txt, bootstrap.sh, lib/Controller/CMakeLists.txt, lib/PhasarClang/CMakeLists.txt, lib/PhasarLLVM/DataFlowSolver/WPDS/CMakeLists.txt, lib/PhasarLLVM/Passes/CMakeLists.txt, lib/PhasarLLVM/Plugins/CMakeLists.txt, lib/PhasarLLVM/Pointer/CMakeLists.txt, lib/PhasarLLVM/TypeHierarchy/CMakeLists.txt, lib/PhasarLLVM/Utils/CMakeLists.txt, lib/PhasarPass/CMakeLists.txt, lib/Utils/CMakeLists.txt, tools/boomerang/CMakeLists.txt, tools/example-tool/CMakeLists.txt, tools/phasar-clang/CMakeLists.txt, tools/phasar-llvm/CMakeLists.txt, utils/install-llvm.sh
The build was assuming that boost was installed to the default system
location and accessible, however for using this as a library I want to
use a custom installed boost to match the version of boost used by the
application. Most of the changes to CMakeLists are to use find_package
to locate the desired boost libraries. I believe this is the preferred
way to include boost libraries.
Also, this changed to allow llvm to be installed to a specified
directory. This change allows the developer to work with multiple
different versions for different projects.
The bootstrap.sh changes include:
- This also includes a change to specify the exact directory for phasar
to be installed to. This allows the developer to have multiple
installations.
- The git submodule init / update was required for a …
=> Fix build to allow custom boost, llvm and phasar directories.

bootstrap.sh
This fixes the bootstrap script to use the proper LLVM dir for using the
proper clang version to compile Phasar.
=> Fix typo for LLVM Directory.

include/phasar/PhasarLLVM/Pointer/LLVMPointsToGraph.h, lib/PhasarLLVM/ControlFlow/Resolver/OTFResolver.cpp, lib/PhasarLLVM/Pointer/LLVMPointsToGraph.cpp
Changes the merge logic for points-to graph to avoid re-creating the
ValueVertexMap from scratch each time.  When merging we can ask boost to
provide a mapping so we can simply append to the existing ValueVertexMap
instead.  For large applications this makes a measurable runtime
improvement since the number of merge calls is large.
I verified with a small application which does some virtual function calls that the resulting callgraph before/after this change were identical.
=> Refactor Points-To graph merge logic.

include/phasar/DB/ProjectIRDB.h, include/phasar/PhasarLLVM/ControlFlow/LLVMBasedICFG.h, lib/DB/ProjectIRDB.cpp, lib/PhasarLLVM/ControlFlow/LLVMBasedICFG.cpp, lib/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchy.cpp, unittests/PhasarLLVM/ControlFlow/LLVMBasedBackwardCFGTest.cpp, unittests/PhasarLLVM/ControlFlow/LLVMBasedCFGTest.cpp, unittests/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchyTest.cpp, unittests/PhasarLLVM/TypeHierarchy/TypeGraphTest.cpp, unittests/Utils/LLVMShorthandsTest.cpp
The largest change performance wise is the change to the graph type to
use a vector for edge storage.
The merge function now mirrors the changes to the Points-To class to
avoid re-building the FunctionVertexMap from scratch.
Changes in constructionWalker avoid fetching the same data multiple
times back-to-back.
printAsDot was modified to allow the user to skip the edge labels,
because those are quite expensive.  Moved code out of the header that is
only used internally to this function body.
ProjectIRDB.h does not use the LLVMPointsToGraph.h, so it was removed
which necessitated several other header changes.
=> ICFG Optimizations -- graph merging and others.

include/phasar/PhasarLLVM/Pointer/LLVMPointsToGraph.h, lib/PhasarLLVM/Pointer/LLVMPointsToGraph.cpp
The call to Value->users() is quite expensive.  Because the result
should not change between executions, we can cache the results for each
Vertex of the points-to graph.  This has a significant performance
improvement.
Changing the graph's backing data structure edge type to use a vector
instead of a set also improves performance.
This change also modifies the n^2 loop to be n^2/2 as described in the
comments -- the inner loop was previously starting at the beginning of
the map instead of at the next item in the map, and we can avoid looking
up in the map by using the appropriate iterators.  These changes did not
significantly impact performance, however the resulting code is more
concise.
=> Optimize calls to get the Users for a a points-to vertex.

lib/PhasarLLVM/DataFlowSolver/Mono/CMakeLists.txt, lib/Utils/CMakeLists.txt
Removes unused dependency to link lto against phasar_utils.
Furthermore, adds needed dependency to phasar_mono.
=> Removes cyclic linking dependency for VaRA-LTO

include/phasar/Utils/BitVectorSet.h
Const qualifying a setter functions does not work and leads to compile
errors, therefore, we remove the const version of the setBits function.
=> Removes const version of bits setter function in BitVectorSet

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDEInstInteractionAnalysis.h
Using virtual methods in constructors can have unexpected behaviour as
the virtual call will not consider more derived classes. Therefore, we
should fully qualify the function call to make it explicit which
function should be called during construction.
=> Fully qualify ZeroValue call for IDEInstInteractionA ctor

bootstrap_docker.sh
Docker image does not build because utils/install-llvm.sh expects 4 arguemnts. The install directory was missing, so I added a sensible default.
=> docker: image build fix

include/phasar/Controller/AnalysisController.h, include/phasar/PhasarLLVM/ControlFlow/LLVMBasedICFG.h, include/phasar/PhasarLLVM/Pointer/LLVMPointsToGraph.h, include/phasar/PhasarLLVM/Pointer/LLVMPointsToInfo.h, include/phasar/PhasarLLVM/Pointer/PointsToInfo.h, include/phasar/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchy.h, lib/Controller/AnalysisController.cpp, lib/PhasarLLVM/ControlFlow/LLVMBasedICFG.cpp, lib/PhasarLLVM/Pointer/LLVMPointsToGraph.cpp, lib/PhasarLLVM/Pointer/LLVMPointsToInfo.cpp, lib/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchy.cpp, tools/phasar-llvm/phasar-llvm.cpp
Hey Phasar folks!
Here is a non-Docker-related PR 🙂
I noticed that exporting to JSON is not exposed on the CLI. So I added this feature. I find this useful for post-processing Phasar's analysis results.
Thanks for the great tool!
=> Expose emit JSON

Dockerfile, utils/install-llvm.sh
The Docker build broke with the update to LLVM 10.
I also disabled the inclusion of LLVM tests to keep the image size and build times down.
=> docker: fixes for LLVM 10

CMakeLists.txt, cmake/phasar_macros.cmake, lib/PhasarClang/CMakeLists.txt, lib/PhasarLLVM/Plugins/CMakeLists.txt, lib/Utils/CMakeLists.txt, tools/boomerang/CMakeLists.txt, tools/example-tool/CMakeLists.txt, tools/phasar-clang/CMakeLists.txt, tools/phasar-llvm/CMakeLists.txt
Since LLVM 10 it is not recommended to build multiple small shared libraries. Instead, users are supposed to use the combined libraries of LLVM and Clang. This commit implements a check for the presence of that library and links against it on success, otherwise the multiple shared libraries are resolved properly, which was slightly broken before as well. Also, the clang-cpp library is properly resolved and linked against. In summary, phasar builds again for me both with the llvm/clang bootstrapped from bootstrap.sh and the Gentoo system installation of llvm:10/clang:10. Testing on Mac OS would be appreciated.
=> Fix build against LLVM-10 fat shared lib.

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/FlowEdgeFunctionCache.h, include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/IFDSIDESolverConfig.h, include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/IDESolver.h, include/phasar/Utils/EnumFlags.h, include/phasar/Utils/Logger.h, lib/PhasarLLVM/DataFlowSolver/IfdsIde/IFDSIDESolverConfig.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/CMakeLists.txt, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDELinearConstantAnalysis_DotTest.cpp
- Use an enum instead of boolean flags in IFDSIDESolverConfig
- Enable emitting the Dot graph programatically (not only through the phasar-llvm interface)
- Annotate intra-edges in the dot graph with the computed edge functions instead of the composed edge functions
=> ESG as dot graph

bootstrap.sh, utils/install-llvm.sh
Modify the install scripts to add the LLVM and Phasar paths for the
dynamic linker.  This removes the need to set the LD_LIBRARY_PATH both
for Phasar and any applications using Phasar as a library.
=> Add LLVM & Phasar paths to dynamic linker.

Dockerfile
Dockerfile now adds LLVM Libraries to LD_LIBRARY_PATH.
Otherwise, phasar-llvm cannot be used in the Docker Container.
=> Fix Shared Library Link for Docker

cmake/phasar_macros.cmake, include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/IDESolver.h, include/phasar/PhasarLLVM/Utils/DOTGraph.h, lib/PhasarLLVM/Utils/DOTGraph.cpp, unittests/CMakeLists.txt, unittests/PhasarLLVM/ControlFlow/LLVMBasedBackwardCFGTest.cpp, unittests/PhasarLLVM/ControlFlow/LLVMBasedCFGTest.cpp, unittests/PhasarLLVM/ControlFlow/LLVMBasedICFGTest.cpp, unittests/PhasarLLVM/ControlFlow/LLVMBasedICFG_CHATest.cpp, unittests/PhasarLLVM/ControlFlow/LLVMBasedICFG_DTATest.cpp, unittests/PhasarLLVM/ControlFlow/LLVMBasedICFG_OTFTest.cpp, unittests/PhasarLLVM/ControlFlow/LLVMBasedICFG_RTATest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/CMakeLists.txt, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDEInstInteractionAnalysisTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDELinearConstantAnalysisTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDELinearConstantAnalysis_DotTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IFDSConstAnalysisTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IFDSTaintAnalysisTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IFDSUninitializedVariablesTest.cpp, unittests/PhasarLLVM/DataFlowSolver/Mono/InterMonoFullConstantPropagationTest.cpp, unittests/PhasarLLVM/DataFlowSolver/Mono/InterMonoTaintAnalysisTest.cpp, unittests/PhasarLLVM/Pointer/LLVMPointsToSetTest.cpp, unittests/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchyTest.cpp, unittests/PhasarLLVM/TypeHierarchy/TypeGraphTest.cpp, unittests/PhasarLLVM/Utils/CMakeLists.txt, unittests/PhasarLLVM/Utils/TaintConfigurationTest.cpp, unittests/TestUtils/TestConfig.h, unittests/Utils/LLVMShorthandsTest.cpp
Adds extra cmake target check-phasar-unittests, for running all
unittests. Refactors tests access to test ll files and extracts direct config usage, making config values easier exchangeable for testing.
=> Integrates phasar testing into cmake

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/IDESolver.h
Fix bug in IDESolver.h and implement the sort function.
After the change, the program can show the analysis result of LLVM IR code in the correct order.
There is an example of output **BEFORE FIX THE BUG** by calling `IDESolver.dumpResults()`
```
***************************************************************
*                  Raw IDESolver results                      *
***************************************************************
============ Results for function 'main' ============
N: %9 = sdiv i32 %7, %8 | ID: 18
--------------------------------
D: @zero_value = constant i2 0 | ID: -1 | V: Bottom
D: %2 = alloca i32 | ID: 7 | V: 20
D: %5 = load i32, i32* %3 | ID: 13 | V: -1
D: %1 = alloca i32 | ID: 6 | V: 0
D: %3 = alloca i32 | ID: 8 | V: 0
D: %7 = load i32, i32* %2 | ID: 16 | V: 20 …
```
=> Fix bug in IDESolver.h and implement the sort function

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/IDESolver.h, include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/JumpFunctions.h
For all n_t, d_t combinations, only a very small amount has more than
one source-value entry, to reduce memory overhead, we replace the map
with a SmallVector.
=> Replaces JumpFunction value map with SmallVector

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDEInstInteractionAnalysis.h
All functions that are accessed by some FlowFunction only refer to
acctually static code that is not related to the specific problem
object. Hence, we can make these functions static and remove problem
references in the FlowFunctions.
=> Removes not neeeded Problem refs for IIaA

include/phasar/PhasarLLVM/Pointer/LLVMBasedPointsToAnalysis.h, lib/PhasarLLVM/Pointer/LLVMBasedPointsToAnalysis.cpp, lib/PhasarLLVM/Pointer/LLVMPointsToSet.cpp
Reenables erasing of already processed AliasAnalysis data, which is
integrated into phasars internal analysis PointsToSets. Erasing old data
is necessary because, otherwise, the data consumes to much memory when
analyzing on larger programs.
=> Reenable clean up of AliasAnalysis data after usage

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/IFDSTabulationProblem.h, include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/IDESolver.h
This allows users to adapt the problem/solver config after creating a
solver from the config.
=> User config refs so the solver and problem share the same config

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/EdgeFunctions.h, include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDEInstInteractionAnalysis.h, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeLists.txt, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/EdgeFunctionComposerTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/EdgeFunctionSingletonFactoryTest.cpp
Some EdgeFunctions are allocated very often during analysis but only hold constant data, to reduce the memory consumption of these EdgeFunctions this commit introduces a SingletonFactory. With the SingletonFactory EdgeFunction implements can automatically reuse previously allocated EdgeFunctions that have the same internal data, saving large amounts of memory in cases where an EdgeFunction would be allocated many times.
=> Implements EdgeFunctionSingletonFactory

lib/Config/CMakeLists.txt, lib/Config/phasar_config-config.cmake, lib/Controller/phasar_controller-config.cmake, lib/DB/CMakeLists.txt, lib/PhasarClang/phasar_clang-config.cmake, lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeLists.txt, lib/PhasarLLVM/DataFlowSolver/IfdsIde/phasar_ifdside-config.cmake, lib/PhasarLLVM/DataFlowSolver/WPDS/phasar_wpds-config.cmake, lib/PhasarLLVM/Passes/phasar_passes-config.cmake, lib/PhasarLLVM/Plugins/phasar_plugins-config.cmake, lib/PhasarLLVM/Pointer/phasar_pointer-config.cmake, lib/PhasarLLVM/TypeHierarchy/phasar_typehierarchy-config.cmake, lib/PhasarLLVM/Utils/phasar_phasarllvm_utils-config.cmake, lib/PhasarPass/phasar_pass-config.cmake, lib/Utils/phasar_utils-config.cmake
On ubuntu 20 using phasar as a library was broken:
CMake Error at CMakeLists.txt:12 (add_executable):
Target "myphasartool" links to target "Boost::graph" but the target was not
found. Perhaps a find_package() call is missing for an IMPORTED target, or
an ALIAS target is missing?
…
this PR should fix this by triggering searches for the dependent boost components through phasar_*-config.cmake.
@vulder Please check whether this breaks the in-tree build in vara. I was unable to build vara with the current state of the phasar development branch.
=> fix search for boost when using phasar as library

include/phasar/PhasarLLVM/ControlFlow/LLVMBasedICFG.h, lib/PhasarLLVM/ControlFlow/LLVMBasedICFG.cpp
An existing function, getDependencyOrderedFunctions(), does have the
ability to get all of the functions from the callgraph. However, this
does extra work to walk the graph such that the functions are returned
in a particular order.  This new function returns the functions in a set
so that we can quickly identify if a given function from the input is
within the graph.  A flat set was chosen for efficiency of space and
speed of lookups.
=> Add ability to get a set of all functions in the callgraph.

bootstrap.sh, utils/install-llvm.sh
Specifically, this fixes the changes originally in commit
6abfaaa60ffb2bc6e5799fe152eedf8654651c69 which was partially lost with
the latest merge of the development branch.  Without this, the
bootstrap.sh script can get hung up on the call to "addLibraryPath"
which is missing.
=> This fixes some merge issues with the install-llvm script.

include/phasar/Utils/BitVectorSet.h, include/phasar/Utils/Table.h
Add branch likleyhood information because the condition will only be
true once, in the case where we exit the function.
=> Small speed improvements for BitVector and Table

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/FlowEdgeFunctionCache.h, include/phasar/Utils/EquivalenceClassMap.h, unittests/Utils/CMakeLists.txt, unittests/Utils/EquivalenceClassMapTest.cpp
Improves memory consumption by compressing keys of maps under a huge load and switching certain maps to a new EquivalenceClassMap, which only keeps one representative value for each equivalence class of keys.
Furthermore, unnecessary count checks were removed by direct look up of the keys, which saves one map traversal for every look up.
=> Makes memory improvements in FlowEdgeFunctionCache

include/phasar/PhasarLLVM/Pointer/LLVMPointsToInfo.h, lib/PhasarLLVM/Pointer/LLVMPointsToInfo.cpp, lib/PhasarLLVM/Pointer/LLVMPointsToSet.cpp
The implementation of retrieveFunction does not need to include a const_cast
since it's implementation does not require non const accesses. Hence, we
should push the burden of const casting to callers that require non
const functions, preserving constness for callers that don't.
=> Moves const_cast out of retrieveFunction

bootstrap.sh, utils/setEnvironmentVariables.sh
Add a bash script to the `utils` folder which sets the environment variables after the PhASAR installation. It appends the export commands to the `~/.$(basename $SHELL)rc` file.
Install (`--needed`) packages if they are not already installed.
=> Update bootstrap script (set ENV variables & shorten arch installation)

CMakeLists.txt
If a system has a bundled library e.g. `libLLVM-XX.so` **and** small libraries like
`libclangSerialization.so`, `libLLVMMCDisassembler.so`, `libclang.so`, `...` installed, cmake will find both. This leads to the following problem:
```
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
Search in the specified paths only
=> LLVM fat lib fix

lib/PhasarLLVM/Pointer/TypeGraphs/CachedTypeGraph.cpp
Issue can be reproduced with debug build of LLVM. This fixes the issue by handling literal structs properly.
=> Fix https://github.com/secure-software-engineering/phasar/issues/194

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/IDESolver.h
Clang static analyze finds the issue that D1FactId could be nullptr,
however, the code looks fine. Hence, we place an assert here to make
sure this case never actually happens during an analysis run.
=> Add assert to guarantee that D1FactId is not a nullptr

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/IDESolver.h
Reverts secure-software-engineering/phasar#215
D1FactId is not a pointer.
=> Revert "Add assert to guarantee that D1FactId is not a nullptr"

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/IDESolver.h
Clang static analyze finds the issue that D1_FSG could be nullptr,
however, the code looks fine. Hence, we place an assert here to make
sure this case never actually happens during an analysis run.
=> Add assert to guarantee that D1_FSG is not a nullptr

include/phasar/Utils/BitVectorSet.h
I found a boundary-value-bug at l.261 of erase() in BitVectorSet.h.
In this code, we cannot erase the first element because of underflow.
So change the condition check to the same as that at l.278 of count() in BitVectorSet.h.
Please review this change.
=> Fixed boundary-value-bug of erase() in BitVectorSet.h

lib/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchy.cpp, test/llvm_test_code/type_hierarchies/CMakeLists.txt, test/llvm_test_code/type_hierarchies/type_hierarchy_14.cpp, test/llvm_test_code/type_hierarchies/type_hierarchy_15.cpp, unittests/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchyTest.cpp
in methods like removeStructOrClassPrefix, ltrim is used to remove a prefix
from a name, which may be wrong. According to the comments of ltrim, ltrim
removes all chars belonging to the prefix from the target string, instead
of removing the prefix directly. The right way is simply removing the prefix
using drop_front
=> Fix some bugs in LLVMTypeHierarchy.cpp

CMakeLists.txt
The generated config file needs to placed in the CURRENT_BINARY_DIR not
just the BINARY_DIR. In cases where phasar is embedded, e.g., in the case of an llvm in-tree build, the binary dirs differ and break the build.
=> Fixes config file generation location

README.md, include/phasar/Config/Version.h, include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/IDESolver.h, include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/IFDSSolver.h
Hi Flo,
please check out if you can make use of this additional API to query the data-flow results respecting LLVM's SSA representation. I did not yet test it extensively, but it should do the trick (at least for some minor test programs).
Cheers
Philipp
=> F additional result iface for llvm

lib/PhasarLLVM/Pointer/LLVMPointsToSet.cpp
Previously points-to relations of globals that were not used directly in a function were omitted. If a callee of that function introduces an alias, it was not propagated further up.
=> Fix points-to information for globals

utils/install-llvm.sh
Switch from one library for each LLVM component to a single library for all components as recommended by LLVM.
> BUILD_SHARED_LIBS is only recommended for use by LLVM developers. If you want to build LLVM as a shared library, you should use the LLVM_BUILD_LLVM_DYLIB option.
https://llvm.org/docs/CMake.html
BUILD_SHARED_LIBS:DEFAULT=Off
LLVM_LINK_LLVM_DYLIB=ON ⇒ LLVM_BUILD_LLVM_DYLIB=ON
---
This PR also removes one extinct flag
```
CMake Warning:
Manually-specified variables were not used by the project:
LLVM_ENABLE_CXX1Y
```
=> Link against libLLVM.so

lib/PhasarLLVM/ControlFlow/Resolver/DTAResolver.cpp
=> Avoid unused variable warning by only iterating if necessary

lib/Utils/LLVMShorthands.cpp
// https://llvm.org/docs/LangRef.html#llvm-var-annotation-intrinsic
=> Add shorthands  Var Annotation Intrinsics

lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IFDSConstAnalysis.cpp
F0417 21:53:52.651166   10192 logging.cc:107] assert.h assertion failed at third_party/llvm/llvm-project/llvm/lib/IR/Value.cpp:104 in llvm::Value::~Value(): materialized_use_empty() && "Uses remain when a value is destroyed!"
=> Fix "Uses remain when a value is destroyed!"

include/phasar/PhasarLLVM/Utils/TaintConfiguration.h
Fix abort caused by missing or wrong file path to source and sink config file. Use default sink and source functions instead.
This PR should solve the problem described in issue https://github.com/secure-software-engineering/phasar/issues/245.
=> Fix for faulty file path in TaintConfiguration

lib/PhasarLLVM/ControlFlow/Resolver/Resolver.cpp
TH can be a `nullptr` if a type hierarchy is not provided.
=> check the resolver's type hierarchy exists before dereferencing it

lib/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchy.cpp
…hen a value is destroyed!" due to incorrect nesting for deleteValue()
=> Fix llvm::Value::~Value(): materialized_use_empty() && "Uses remain..

unittests/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeLists.txt
Only add TSAN when compiled with clang and ASAN is not active.
=> Only add TSAN for testing when compatible

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDEInstInteractionAnalysis.h, include/phasar/PhasarLLVM/Pointer/LLVMPointsToGraph.h, include/phasar/PhasarLLVM/Pointer/LLVMPointsToSet.h, include/phasar/PhasarLLVM/Pointer/PointsToInfo.h, lib/PhasarLLVM/Pointer/LLVMPointsToGraph.cpp, lib/PhasarLLVM/Pointer/LLVMPointsToSet.cpp
Extends the PointsToInfo interface with a query method
`isInReachableAllocationSites`. This enables users to simply query if a
value is in the set of reachable allocation sites without needing to
return a copy of the set.
=> Adds a query method for possible allocation sites to PointsToInfo

lib/PhasarLLVM/DataFlowSolver/IfdsIde/IFDSFieldSensTaintAnalysis/FlowFunctions/StoreInstFlowFunction.cpp
Reverts secure-software-engineering/phasar#358
kinda conflicts with #360 
also, std::basic_string doesn't have contains until C++23, currently in phasar we're at C++17.
=> Revert "Update StoreInstFlowFunction.cpp"

CMakeLists.txt, tools/boomerang/CMakeLists.txt, tools/example-tool/CMakeLists.txt, tools/phasar-clang/CMakeLists.txt, tools/phasar-llvm/CMakeLists.txt
Some phasar tools started to switch from boost::filesystem to
std::filesystem, so we need to link these targets against the std
filesystem library.
=> Link stdc++fs for tools that require it

include/phasar/Utils/LLVMShorthands.h, lib/Utils/LLVMShorthands.cpp
Small clean up. Removes const from the return type, as returning a value
will result in a copy, hence, making it const has no meaning.
Furthermore, relayouts the function a bit so the three parts are easier
understandable.
=> Cleans up getVarAnnotationIntrinsicName

lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDELinearConstantAnalysis.cpp, test/llvm_test_code/linear_constant/overflow_add.cpp, test/llvm_test_code/linear_constant/overflow_div_min_by_neg_one.cpp, test/llvm_test_code/linear_constant/overflow_mul.cpp, test/llvm_test_code/linear_constant/overflow_sub.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDELinearConstantAnalysisTest.cpp
In a the cases that the add/sub/mul operation overflows, we need to set
the edge function lattice (l_t) to TOP.
=> Fixes signed integer overflow in LinearConstantAnalysis 

lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDELinearConstantAnalysis.cpp, test/llvm_test_code/linear_constant/ub_division_by_zero.cpp, test/llvm_test_code/linear_constant/ub_modulo_by_zero.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDELinearConstantAnalysisTest.cpp
Should we encounter a division(module) by zero, which is UB, in the
program under analysis, we set the lattice(l_t) value to TOP.
=> Fixes UB handling in LinearConstantAnalysis

CMakeLists.txt
Switch to building unit tests by default for better code quality.  Right now since tests are not built by default it is easy by default to make a breaking change or not update tests when changing code.
=> Switch to building Unit Tests by default

lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDELinearConstantAnalysis.cpp
In some cases we don't get a return value, hence, we need to correctly
kill the flow facts at this point and not return an LCAFF.
=> Fixes handling for non existent return values

include/phasar/PhasarLLVM/ControlFlow/LLVMBasedICFG.h
With IncludeGlobals == false the call graph and points-to information may be unsound.
=> Default IncludeGlobals to on for soundness

include/phasar/PhasarLLVM/ControlFlow/LLVMBasedBackwardICFG.h, lib/PhasarLLVM/ControlFlow/LLVMBasedBackwardICFG.cpp
requires #419 to be merged first.
=> insert dummy return instructions in each function in the backward ICFG to get consistency w.r.t. forward ICFG

include/phasar/Utils/LLVMShorthands.h, lib/DB/ProjectIRDB.cpp, lib/PhasarLLVM/ControlFlow/LLVMBasedICFG.cpp, lib/Utils/LLVMShorthands.cpp
... for printing llvm::Value - make sure that destruction of an llvm::Module leads to  destruction of its llvm::ModuleSlotTracker in cache
please merge #423 first.
=> fix caching of llvm::ModuleSlotTracker instances 

CMakeLists.txt, lib/PhasarLLVM/DataFlowSolver/Mono/CMakeLists.txt, lib/PhasarLLVM/DataFlowSolver/Mono/phasar_mono-config.cmake, lib/PhasarLLVM/TaintConfig/CMakeLists.txt, lib/PhasarLLVM/TaintConfig/phasar_taintconfig-config.cmake
Fixes linking issues of taintconfig and adds a workaround to include the
schema validator in LLVM_EXPORT for in tree builds, so llvm correctly
installs the schema lib alongside it's tools/libs.
=> Fixes linking issues of taintconfig + json workaround

unittests/PhasarLLVM/ControlFlow/LLVMBasedCFGTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDEExtendedTaintAnalysisTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDEInstInteractionAnalysisTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IFDSConstAnalysisTest.cpp, unittests/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchyTest.cpp, unittests/TestUtils/TestConfig.h
This is needed as LLVM currently ships with an older version of gtest
(<1.10.0) that does not support GTEST_SKIP.
=> Disable tests that use GTEST_SKIP for IN_TREE builds.

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDEInstInteractionAnalysis.h
For cases where the EdgeFactGenerator needs to generate initial facts for globals, we need to pass it to the ctor of the analysis because the IDESolver computes the facts for global initial seeds on construction.
=> Extends the IDEInstInteractionAnalysis constrution with an EdgeFactGenerator

Dockerfile
Updated LLVM version in the Dockerfile to match the project's requirements.
Also changed the ubuntu image version from latest to a fixed version (20.04), since the newest ubuntu version 21.10 doesn't work with LLVM 12.0.0 and they might update their latest tag at some point.
I'm currently working on a multistage Dockerfile to increase performance. I experimented with GitHub Actions and building the current Dockerfile with an action takes around 4 hours, which is not sufficient.
=> Fixed Dockerfile 

include/phasar/PhasarLLVM/Pointer/LLVMPointsToGraph.h, include/phasar/PhasarLLVM/Pointer/LLVMPointsToSet.h, include/phasar/PhasarLLVM/Pointer/PointsToSetOwner.h
Replace std::pmr::* with LLVM's allocators in PointsToSetOwner -- Need to discuss about general strategy of dealing with allocators (the default strategy to always use the STL types doesn't seem to work anymore)
=> PMR Compatibility Workaround

include/phasar/PhasarLLVM/ControlFlow/Resolver/Resolver.h, include/phasar/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchy.h, include/phasar/PhasarLLVM/TypeHierarchy/LLVMVFTable.h, lib/PhasarLLVM/ControlFlow/Resolver/CHAResolver.cpp, lib/PhasarLLVM/ControlFlow/Resolver/DTAResolver.cpp, lib/PhasarLLVM/ControlFlow/Resolver/OTFResolver.cpp, lib/PhasarLLVM/ControlFlow/Resolver/RTAResolver.cpp, lib/PhasarLLVM/ControlFlow/Resolver/Resolver.cpp, lib/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchy.cpp, lib/PhasarLLVM/TypeHierarchy/LLVMVFTable.cpp
llvm-link collapsed multiple C++  types with identical members to one single LLVM type. The current  virtual function call resolution then only considers the VTable of the LLVM type that represents all of the collapsed type. Now, we look for all VTables that the function pointer aliases with and extract the possible callees from them.
=> fix VTables for collapsed types. 

include/phasar/Utils/LLVMShorthands.h
This is needed, as older gcc versions do not consider the member
declaration as an explicit ctor call.
=> Add curly braces to explicit call the ctor of SmallDenseMap

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/IFDSFieldSensTaintAnalysis/FlowFunctions/MapTaintedValuesToCaller.h, include/phasar/PhasarLLVM/DataFlowSolver/WPDS/WPDSSolverConfig.h
Older gcc versions confuse the type with the member name if both are the
same and see the second as a redeclaration. This is fixed by explicitly
declaring the types namespace.
=> Fixes gcc redeclaration confusion

lib/PhasarLLVM/ControlFlow/CFG.cpp, lib/Utils/CMakeLists.txt
* phasar_utils requires boost libs and std::filesystem
* operator<< for SpecialMemberFunctionType was not fully ported to llvm streams
=> Fixes linking issues in utils and tests

README.md, bootstrap.sh, utils/InstallAptDependencies.sh, utils/install-llvm.sh
By default the bootstrap script installs PhASAR system-wide. However, this is oftentimes not desired (also there are problems uninstalling phasar once it is installed -- check #556).
This PR fixes this issue by making install through bootstrap.sh optional (you have to explicitly state `--install`).
Also, the README has been adopted.
=> Bootstrap Update

Dockerfile
sudo is not needed inside Dockerfiles
libboost-all-dev got installed twice for some reason, which caused the build to crash.
=> Dockerfile Fixes

lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IFDSTaintAnalysis.cpp
extended taint flow analysis. it now generates a flow for ExtractValue instructions, which are very common in Swift-based LLVM IR.
The pattern we are now able to handle is the following:
```
%3 = call swiftcc { i64, %swift.bridge* } @"Swift.String.init(_builtinStringLiteral: Builtin.RawPointer, utf8CodeUnitCount: Builtin.Word, isASCII: Builtin.Int1) -> Swift.String"(i8* getelementptr inbounds ([13 x i8], [13 x i8]* @.str, i64 0, i64 0), i64 12, i1 true)
%4 = extractvalue { i64, %swift.bridge* } %3, 0
%5 = extractvalue { i64, %swift.bridge* } %3, 1
```
If the result of the method call was tainted we now correctly propagate the taint to %4 and %5
=> Added support for ExtractValueInstruction to IFDS Taint Analysis

include/phasar/PhasarLLVM/Passes/GeneralStatisticsAnalysis.h, lib/PhasarLLVM/Passes/GeneralStatisticsAnalysis.cpp
Including a counter for global constants (seems like u were right @fabianbs96 , most of the globals generated in Swift-based LLVM IR are consts and can be ignored for most cases :) )
=> Minor update to IR Statistics

include/phasar/Config/Configuration.h, include/phasar/DataFlow/IfdsIde/Solver/IDESolver.h, include/phasar/Domain/LatticeDomain.h, include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEInstInteractionAnalysis.h, lib/Config/Configuration.cpp, lib/Controller/AnalysisControllerXIDEIIA.cpp, lib/PhasarLLVM/Pointer/LLVMAliasSet.cpp, test/llvm_test_code/inst_interaction/CMakeLists.txt, test/llvm_test_code/inst_interaction/call_07.cpp, unittests/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEInstInteractionAnalysisTest.cpp
The edge functions in the `IDEInstInteractionAnalysis` sometimes generate dataflows that flow in reverse controlflow direction.
This PR changes that.
Note: This PR also includes changes that are now being out-sourced to #594. So, that PR should probably be merged first
=> Fix IIA reverse flow

include/phasar/PhasarLLVM/Utils/LLVMShorthands.h, lib/PhasarLLVM/ControlFlow/LLVMBasedICFGGlobalsImpl.cpp, lib/PhasarLLVM/Utils/LLVMShorthands.cpp
To handle global constructors and destructors we are generating wrapper functions that call these. In some (rare) cases the generated call-sites was incompatible with the expected callee-signature (some missing pointe-bitcasts).
As this is only checked with debug-assertions on LLVM-side, this error only shows up when using a debug-build of LLVM (for example in the in-tree build).
This PR fixes the issue on phasar side.
=> Fix Crash in GlobalCtorDtor Handling

CMakeLists.txt
Warnings, such as, warning: default label in switch which covers all enumeration values, from nlohmann_json spam during compilation, especially for LLVM builds. A default label for a switch is unreachable should all cases covered. LLVM prefers to warn in cases where not all cases are covered. As we cannot change the code in the json lib, we should at least disable the flood of warnings.
=> Disables warnings in nlohmann_json

lib/PhasarLLVM/DataFlow/IfdsIde/Problems/IFDSTaintAnalysis.cpp
I added a special summary function to our IFDS Taint analysis which specifically handles Swift's String append methods. 
With this extension we are able to find the taint flow from this example if we tag getPassword() as source and db.prepare() as sink. 
```import SQLite
@main
public struct SQLExecutableTaintTest {
public static func main() throws {
let db = try Connection() // in-memory database        
// nameInput and passwordInput represent possible user input 
// and are assumed to be received from external inputs
let nameInput = "'Alice'"
let passwordInput = getPassword() // source 
let queryStringName = "SELECT * FROM users WHERE name=" + 
nameInput + 
" AND password="
let queryString = queryStringName + passwordInput
let stmt = try db.prepare(queryString) // sink
}
// this method …
```
=> IFDS Taint analysis summary function for Swift's  String.append method

include/phasar/DataFlow/IfdsIde/IFDSIDESolverConfig.h, include/phasar/DataFlow/IfdsIde/Solver/IDESolver.h, include/phasar/DataFlow/IfdsIde/Solver/IFDSSolver.h, include/phasar/DataFlow/IfdsIde/SolverResults.h, include/phasar/Utils/Printer.h, tools/example-tool/myphasartool.cpp
The IDESolver has been found to consume a lot of memory, most of it being intermediate results. 
This PR aims at reducing the total memory overhead with two contributions:
1. The default solver configuration no longer enables recording the ESG edges in an additional map (this feature is anyway likely to be deprecated and replaced in the future). This has to be enabled explicitly. Note: `phasar-cli` already disables recordEdges by default
2. The solver results can be moved out of the IDESolver. This allows destructing the solver while retaining the solver results for subsequent analysis. To simplify the process new functions `solveIDEProblem` and `solveIFDSProblem` have been added
=> Consume solver results

include/phasar/Utils/Logger.h, unittests/Utils/CMakeLists.txt, unittests/Utils/LoggerTest.cpp
The logger macros `PHASAR_LOG*` currently only work if used within the namesapce `psr` or in an environment that uses `using namespace psr`. 
This PR fixes that issue.
=> Fix Logger Macros

bootstrap.sh
The `BOOST_VERSION` check inside `bootstrap.sh` returns exit code 1 if boost is not already installed preventing the script from continuing.
=> Fix Boost Installation

.gitignore, lib/PhasarLLVM/Utils/LLVMShorthands.cpp, unittests/Utils/LLVMShorthandsTest.cpp
Phasar currently crashes when the same `llvm::Module` is managed by multiple `LLVMProjectIRDB` instances at the same time. This situation occurrs for example when phasar is used in LLVM's pass infrastructure and multiple phasar-passes are run in one `opt`-call.
Reference-counting the cached ModuleSlotTracker instances fixes this problem.
=> Ref-counted ModuleSlotTracker

include/phasar/DataFlow/IfdsIde/SolverResults.h, include/phasar/PhasarLLVM/DataFlow/IfdsIde/LLVMSolverResults.h, include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEInstInteractionAnalysis.h, lib/AnalysisStrategy/Strategies.cpp
The functions `resultAtInLLVMSSA()` und `resultsAtInLLVMSSA()` in the `SolverResults` crash if called with a non-void instruction that happens to be a terminator of a BasicBlock (e.g. a `invoke` stmt).
As there seems to be no exact solution to computing the resultsAtInLLVMSSA of terminator instructions, this PR provides an approximation that works in most cases.
=> Fix result[s]AtInLLVMSSA()

include/phasar/DataFlow/IfdsIde/InitialSeeds.h, include/phasar/PhasarLLVM/DataFlow/IfdsIde/LLVMSolverResults.h
The default edge value of the `InitialSeeds` for IFDS analyses is `TOP` (the bottom value of the binary lattice) indicating "no information". This is incorrect as holding IFDS dataflow facts semantically have to be annotated with the top value of the binary lattice, which is called `BOTTOM` in phasar.
This issue prevents the `IDESolver` from computing IFDS results at certain call sites.
This PR solves that problem by correctly assigning the `BOTTOM` edge value to the initial seeds of IFDS analyses.
Should fix #629.
=> Fix InitialSeeds for IFDS

lib/PhasarLLVM/TaintConfig/CMakeLists.txt, lib/PhasarLLVM/TaintConfig/LLVMTaintConfig.cpp
The `makeInitialSeeds` function from `LLVMTaintConfig` may generate seeds at skipped (e.g., debug-) instructions leading the IDESolver to produce no IDE edge values generated from those seeds
=> Fix TaintConfig Initial Seeds

include/phasar/PhasarLLVM/DataFlow/IfdsIde/LLVMFlowFunctions.h, include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IFDSTaintAnalysis.h, lib/PhasarLLVM/DataFlow/IfdsIde/Problems/IFDSTaintAnalysis.cpp
Correctness fixes + precision/performance improvements for the IFDSTaintAnalysis.
Related to #643.
=> Fix taint analysis

include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDETypeStateAnalysis.h, include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/CSTDFILEIOTypeStateDescription.h, include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLEVPKDFCTXDescription.h, include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLEVPKDFDescription.h, include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLSecureHeapDescription.h, include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLSecureMemoryDescription.h, include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/TypeStateDescription.h, lib/Controller/AnalysisControllerXIDECSTDIOTS.cpp, lib/Controller/AnalysisControllerXIDEOpenSSLTS.cpp, lib/PhasarLLVM/DataFlow/IfdsIde/Problems/IDETypeStateAnalysis.cpp, lib/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/CSTDFILEIOTypeStateDescription.cpp, lib/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLEVPKDFCTXDescription.cpp, lib/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLEVPKDFDescription.cpp, lib/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLSecureHeapDescription.cpp, lib/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLSecureMemoryDescription.cpp, unittests/PhasarLLVM/DataFlow/IfdsIde/Problems/IDETSAnalysisFileIOTest.cpp, unittests/PhasarLLVM/DataFlow/IfdsIde/Problems/IDETSAnalysisOpenSSLEVPKDFTest.cpp, unittests/PhasarLLVM/DataFlow/IfdsIde/Problems/IDETSAnalysisOpenSSLSecureHeapTest.cpp, unittests/PhasarLLVM/DataFlow/IfdsIde/Problems/IDETSAnalysisOpenSSLSecureMemoryTest.cpp
The typestate analysis is the only analysis in phasar where one printer function (`LToString`) depends on the concrete analysis instance. This is, because the TypestateDescription defines, how a type state should be printed.
Moving to free-printers (#652) would then require to make the type state itself a virtual type that knows how it should printed. This is not only ugly, but may also have a performance impact.
To fix this issue, this PR makes the typestate analysis a template enabling type-safe type states.
=> Template Typestate Analysis

unittests/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEInstInteractionAnalysisTest.cpp
The RVOTest in the IIA depends on a very specific version of libstdc++ and reliably fails on all other systems.
We should get rid of it.
=> Disable IIA RVOTest

include/phasar/DataFlow/IfdsIde/FlowFunctions.h, include/phasar/DataFlow/IfdsIde/Solver/FlowEdgeFunctionCache.h, include/phasar/DataFlow/IfdsIde/Solver/IDESolver.h, include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEInstInteractionAnalysis.h, include/phasar/Utils/Utilities.h
For the change in the IDE solver I am not sure yet how this should be done properly, let's discuss that @fabianbs96
=> Fix handling of unbalanced returns for IIA

.github/workflows/ci.yml
The new Swift version 5.9 produces LLVM IR that is incompatible with the version we use. So pin Swift in the CI to the latest supported  version 5.8.1
=> Pin Swift Version

bootstrap.sh
For `(list)` in bash, `list` is executed in a subshell environment. Variable assignments do not remain in effect after the command completes.
Fix by using `{ list; }`, where `list` is executed in the current shell environment.
=> Fix unexpected subshell execution in bootstrap.sh

include/phasar/PhasarLLVM/TaintConfig/TaintConfigData.h
On my system (Debian Testing aka 13/Trixie), I have to explicitly include cstdint to make Phasar compile.
=> TaintConfigData need include cstdint for uint32_t

lib/PhasarLLVM/Pointer/LLVMBasedAliasAnalysis.cpp, lib/PhasarLLVM/Pointer/external/LLVM-LICENSE.txt, lib/PhasarLLVM/Pointer/external/README.md, lib/PhasarLLVM/Pointer/external/llvm/AliasAnalysisSummary.h, lib/PhasarLLVM/Pointer/external/llvm/CFLAliasAnalysisUtils.h, lib/PhasarLLVM/Pointer/external/llvm/CFLAndersAliasAnalysis.cpp, lib/PhasarLLVM/Pointer/external/llvm/CFLAndersAliasAnalysis.h, lib/PhasarLLVM/Pointer/external/llvm/CFLGraph.h, lib/PhasarLLVM/Pointer/external/llvm/CFLSteensAliasAnalysis.cpp, lib/PhasarLLVM/Pointer/external/llvm/CFLSteensAliasAnalysis.h, lib/PhasarLLVM/Pointer/external/llvm/StratifiedSets.h
As LLVM has removed the CFL-based alias analyses (CFLAndersAliasAnalysis and CFLSteensAliasAnalysis) that PhASAR depends on , we cannot upgrade the LLVM version.
To enable upgrading, we *temporarly* provide a copy of these LLVM analyses in PhASAR's code base.
=> Provide LLVM's CFL-based Alias Analyses

bootstrap.sh
Currently, the custom build of LLVM must be located in /usr/local/llvm-14.
If not, CMake will either fail finding LLVMConfig.cmake or use a different LLVM installation, e.g., the system-wide one. This will, for example, result in an include path different from the custom LLVM installation.
This commit extends the CMake scripts to force the user to specify the variable PHASAR_LLVM_INSTALL_DIR that points to the LLVM installation directory.
This variable is also used to extend CMAKE_PREFIX_PATH which will make CMake use LLVMConfig.cmake from the custom build.
(Fixed #689)
=> Allow LLVM beeing installed in a custom path

include/phasar/DataFlow/IfdsIde/Solver/IDESolver.h, include/phasar/PhasarLLVM/ControlFlow/LLVMBasedICFG.h, include/phasar/PhasarLLVM/DB/LLVMProjectIRDB.h, include/phasar/Utils/DFAMinimizer.h, include/phasar/Utils/MaybeUniquePtr.h, lib/PhasarLLVM/TaintConfig/LLVMTaintConfig.cpp, unittests/Utils/CMakeLists.txt, unittests/Utils/CompilationTests.cpp
Fixes the initial values handling in IDESolver to handle the case that a seed location can be reached from another path.
Additionally fixes the MaybeUniquePtr with incomplete types
=> Misc Fixes
