lib/PhasarLLVM/ControlFlow/Resolver/RTAResolver.cpp, unittests/PhasarLLVM/ControlFlow/LLVMBasedICFGTest.cpp, unittests/PhasarLLVM/ControlFlow/LLVMBasedICFG_CHATest.cpp, unittests/PhasarLLVM/ControlFlow/LLVMBasedICFG_DTATest.cpp, unittests/PhasarLLVM/ControlFlow/LLVMBasedICFG_OTFTest.cpp, unittests/PhasarLLVM/ControlFlow/LLVMBasedICFG_RTATest.cpp
Writing some test cases for CHA, RTA, DTA and OTF call-graph algorithms.
=> Call graph test cases

README.md
See also https://raspberrypi.stackexchange.com/questions/19513/could-not-find-curl-missing-curl-library-curl-include-dir
=> Add dev version of curl for cmake to complete

include/phasar/PhasarLLVM/Mono/Solver/InterMonoSolver.h, unittests/PhasarLLVM/Mono/InterMonoTaintAnalysisTest.cpp
=> Test MonoSolver

unittests/PhasarLLVM/Mono/InterMonoTaintAnalysisTest.cpp
=> Fix issue of inter mono taint unittest

include/phasar/PhasarLLVM/IfdsIde/Solver/LLVMIDESolver.h, include/phasar/PhasarLLVM/Mono/Solver/InterMonoSolver.h, include/phasar/PhasarLLVM/Mono/Solver/LLVMInterMonoSolver.h, include/phasar/PhasarLLVM/Utils/Printer.h
Furthermore, fixes small issues like missing inclues.
=> Adds missing dtors to InterMonoSolver

bootstrap.sh
Improved the installation script `bootstrap.sh` by adding command-line options (`-j` and `-DBOOST_VERSION` for specifying the max number of threads to use and the desired boost version).
=> Improving bootstrap script

include/phasar/PhasarLLVM/ControlFlow/LLVMBasedICFG.h, lib/PhasarLLVM/ControlFlow/LLVMBasedICFG.cpp
Added a few accessor methods for fetching data from the callgraph, and
some modifiers to remove a specific edge or specific vertex.
I also moved some of the function comments to the header file.
=> Add capability to get out edges and to remove graph items.

include/phasar/Utils/BitVectorSet.h
Replacing std::vector<bool> in the BitVectorSet Header with llvm::BitVector and using llvm::BitVector native operations to improve performance.
=> Replace std::vector<bool> with llvm::BitVector

Dockerfile
Sorry, another Docker fix that I missed! The entry point directory was incorrect
=> docker: entrypoint fix

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/IDESolver.h, include/phasar/Utils/Table.h
Cleans up Table and Table::Cell, const qualifying methods, marking methods without side effects nodiscard and adding member accessor methods for Table::Cells.
=> Refactors and cleans up Table methods

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/IDESolver.h, include/phasar/Utils/Logger.h
Merges consecutive debug statements into one.
=> Rework IDESolver debugging

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/IDESolver.h, include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/PathEdge.h, include/phasar/Utils/Table.h
Makes immutable data structures const and removes some unnecessary copies.
=> Polish IDESolver

CMakeLists.txt, cmake/phasar_macros.cmake, lib/PhasarClang/CMakeLists.txt, lib/PhasarLLVM/Plugins/CMakeLists.txt, lib/Utils/CMakeLists.txt, tools/boomerang/CMakeLists.txt, tools/example-tool/CMakeLists.txt, tools/phasar-clang/CMakeLists.txt, tools/phasar-llvm/CMakeLists.txt
Reverts secure-software-engineering/phasar#124
=> Revert "Fix build against LLVM-10 fat shared lib."

CMakeLists.txt, cmake/phasar_macros.cmake, lib/PhasarClang/CMakeLists.txt, lib/PhasarLLVM/Plugins/CMakeLists.txt, lib/Utils/CMakeLists.txt, tools/boomerang/CMakeLists.txt, tools/example-tool/CMakeLists.txt, tools/phasar-clang/CMakeLists.txt, tools/phasar-llvm/CMakeLists.txt
Reverts secure-software-engineering/phasar#125
=> Revert "Revert "Fix build against LLVM-10 fat shared lib.""

Dockerfile, bootstrap.sh, utils/InstallAptDependencies.sh, utils/install-llvm.sh
- Update the bootstrap and llvm install script
- Create `/tmp` files only if necessary
- Make use of the script for apt packages 
- Use pip3 packages
- Use `cmake --build` as suggested by @vulder 
Dockerfile :heavy_check_mark: 
```
FROM ubuntu:latest
RUN apt -y update && apt install bash sudo git -y
RUN mkdir -p /usr/src/phasar
WORKDIR /usr/src/phasar
COPY utils/InitializeEnvironment.sh /usr/src/phasar/utils/InitializeEnvironment.sh
RUN /usr/src/phasar/utils/InitializeEnvironment.sh
COPY . /usr/src/phasar
RUN /usr/src/phasar/bootstrap.sh
```
=> Ninja installation fix

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/IDESolver.h
Directly initialize jump function value from look ups. Furthermore, this
prevents jump function look ups to create empty jump function entries.
=> Refactors IDE jump function initializer

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/FlowEdgeFunctionCache.h
Grouping both n_ts and d_ts into keys together creates keys that appear
more often, creating a denser packing of values in the two maps and,
therefore, saving memroy.
=> Refactor NormalEdgeFunctionCache to better compress keys

bootstrap.sh
Fixing the variable name that contains the number of threads.
=> Using correct bash variable for threads

Dockerfile
The LLVM build_dir was missing.
=> docker: install-llvm.sh was missing an argument

CMakeLists.txt, include/phasar/Utils/Utilities.h, lib/DB/CMakeLists.txt, lib/DB/ProjectIRDB.cpp, lib/PhasarLLVM/ControlFlow/CMakeLists.txt, lib/PhasarLLVM/ControlFlow/LLVMBasedCFG.cpp, lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeLists.txt, lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDESecureHeapPropagation.cpp, lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDETypeStateAnalysis.cpp, lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IFDSConstAnalysis.cpp, lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IFDSTaintAnalysis.cpp, lib/PhasarLLVM/Passes/CMakeLists.txt, lib/PhasarLLVM/Passes/GeneralStatisticsAnalysis.cpp, lib/Utils/CMakeLists.txt, lib/Utils/Utilities.cpp, unittests/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchyTest.cpp
This helps with windows demangle support and ties phasars behaviour more
with llvm behaviour.
=> Replaces boost demangle with llvm's own demangle

lib/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchy.cpp
Added the necessary checks to prevent the assertion check fail.
=> Fix Assertion Violation

include/phasar/PhasarLLVM/ControlFlow/LLVMBasedICFG.h, include/phasar/PhasarLLVM/ControlFlow/Resolver/OTFResolver.h, include/phasar/Utils/LLVMShorthands.h, lib/PhasarLLVM/ControlFlow/LLVMBasedICFG.cpp, lib/PhasarLLVM/ControlFlow/Resolver/OTFResolver.cpp, lib/PhasarLLVM/Pointer/LLVMPointsToSet.cpp, lib/Utils/LLVMShorthands.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IFDSConstAnalysisTest.cpp
This fixes several bugs that lead to potentially incomplete callgraphs, see https://github.com/secure-software-engineering/phasar/issues/206
Please review and merge https://github.com/secure-software-engineering/phasar/pull/211 first as callgraph dot export benefits greatly from that as well.
=> Fix C-style polymorphism

CMakeLists.txt, config.h.in, lib/PhasarLLVM/Passes/ExampleModulePass.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDEInstInteractionAnalysisTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDELinearConstantAnalysisTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDELinearConstantAnalysis_DotTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDETSAnalysisFileIOTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDETSAnalysisOpenSSLEVPKDFTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDETSAnalysisOpenSSLSecureHeapTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDETSAnalysisOpenSSLSecureMemoryTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IFDSConstAnalysisTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IFDSTaintAnalysisTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IFDSUninitializedVariablesTest.cpp, unittests/PhasarLLVM/DataFlowSolver/Mono/InterMonoFullConstantPropagationTest.cpp, unittests/PhasarLLVM/DataFlowSolver/Mono/InterMonoTaintAnalysisTest.cpp, unittests/PhasarLLVM/WPDS/Problems/WPDSLinearConstantAnalysisTest.cpp, unittests/TestUtils/TestConfig.h, unittests/Utils/LLVMIRToSrcTest.cpp
* An error in ExampleModulePass (see code change)
* Fix a few memory leaks in unittests (some objects are not deleted in teardown routines)
=> Fix a few minor issues

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/LLVMIFDSSummaryGenerator.h
=> Remove non-existant header

lib/PhasarLLVM/Passes/ValueAnnotationPass.cpp
=> Update PassSupport.h to Pass.h

lib/PhasarLLVM/Pointer/TypeGraphs/LazyTypeGraph.cpp
=> Delete unused variable

lib/DB/ProjectIRDB.cpp
=> Add .str() to StringRef

lib/PhasarLLVM/Passes/GeneralStatisticsAnalysis.cpp
=> Update GeneralStatisticsAnalysis.cpp to migrate to llvm/Pass.h

lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IFDSFieldSensTaintAnalysis.cpp
=> Add .str() to isSink call

include/phasar/Utils/LLVMShorthands.h
=> Add header support for #322

include/phasar/PhasarLLVM/ControlFlow/LLVMBasedCFG.h
=> Remove forward declaration and replace with proper include for llvm::Function

include/phasar/PhasarLLVM/Domain/AnalysisDomain.h
=> Replace forward declarations with #includes

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDEInstInteractionAnalysis.h, include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Solver/SolverResults.h
Splits up the variable tracking functions into one accessor for empty
variables and another that returns all variables.
=> Refactors IDEInstInteractionAnalysis variable tracking function

lib/Utils/LLVMShorthands.cpp
Adds check to isStaticVariableLazyInitializationBranch, so we don't
access a CalledFunction if none exists.
=> Fixes undefined behavior in isStaticVariableLazyInitializationBranch

CMakeLists.txt
This should go with the unit tests change
=> Default to building test IR Code

lib/PhasarLLVM/ControlFlow/LLVMBasedICFG.cpp
Need to ignore dbg statements if desired
=> Fix getReturnSitesOfCallAt()

utils/setEnvironmentVariables.sh
This fixes a runtime error caused by a missing path entry.
closes https://github.com/secure-software-engineering/phasar/issues/484 .
=> added missing LD_LIBRARY_PATH export to nested folder

lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IFDSUninitializedVariables.cpp
fix unreachable code in IFDSUninitializedVariables, fixing #410
=> fix unreachable code in IFDSUninitializedVariables, fixing #410

lib/PhasarLLVM/ControlFlow/Resolver/Resolver.cpp
The receiver (i.e. the this pointer) is not always the first parameter (index 0). In case of sret (return of large or non-trially movable types) the return value is the first parameter and the receiver is the second
=> Fix getReceiverType() 

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/FlowEdgeFunctionCache.h, include/phasar/Utils/Logger.h, lib/Controller/CMakeLists.txt, lib/PhasarLLVM/Passes/GeneralStatisticsAnalysis.cpp, lib/PhasarLLVM/TypeHierarchy/CMakeLists.txt, lib/PhasarPass/CMakeLists.txt
Fixes debug macro declaraion
Fixes debug macro usages
Fixes thread linking for controller and phasar pass
=> Various fixes (debug macro, linked)

CREDITS.txt
Small update to our heavily out-dated CREDITS.txt file
=> Credits update

CMakeLists.txt, README.md
=> Custom Config-Install-Prefix

include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/EdgeFunctions.h, include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/FlowFunctions.h, include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDELinearConstantAnalysis.h, lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDELinearConstantAnalysis.cpp
As discussed I added a default implementation for the getSummaryFlow and Edge Function
=> Default Summary Flow and Edge Function

unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDETSAnalysisOpenSSLEVPKDFTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDETSAnalysisOpenSSLSecureHeapTest.cpp, unittests/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDETSAnalysisOpenSSLSecureMemoryTest.cpp
OpenSSL tests were disabled during latest pr.
=> fix: make the OpenSSL-based unittests compile

cmake/phasar_macros.cmake
=> Fix library installation on debian 10

Config.cmake.in
=> Fix Install After ReworkFolderStructure

include/phasar/DB/ProjectIRDBBase.h, include/phasar/DataFlow/IfdsIde/EdgeFunction.h, include/phasar/DataFlow/IfdsIde/FlowFunctions.h, include/phasar/PhasarLLVM/Utils/LLVMIRToSrc.h, include/phasar/Utils/MaybeUniquePtr.h, lib/PhasarLLVM/Utils/LLVMIRToSrc.cpp
Smaller fixes/additions that are too small for their own PR
=> Misc fixes

CMakeLists.txt, include/phasar/DataFlow/IfdsIde/EdgeFunction.h
Enabling building phasar with C++20 is a low-hanging fruit...
=> Enable Building Phasar with C++20

lib/PhasarLLVM/DataFlow/IfdsIde/Problems/IDESecureHeapPropagation.cpp
=> CallBase Called Function getName Null Check

unittests/PhasarLLVM/ControlFlow/CMakeLists.txt
=> Fix Linking for LLVMBasedICFGGlobCtorDtorTest

Config.cmake.in
=> Fix Legacy phasar_config
